# Generated by Django 4.0.1 on 2022-08-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
